version: "3"
services:
  web:
    build: 
      context: . # take the docker file in current directory and build the image (this syntax usefull when we have custom name for dockerfile)
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app # map the current directory on the local folder to app folder in the container
  tests:  # to run a live tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

